# frozen_string_literal: true

module Serverless
  module Aws
    module Ruby
      # create an http event as generated by API Gateway
      class HttpRequestEvent
        attr_accessor :method, :path, :body
        attr_reader :request_context, :headers, :query, :path_parameters, :multi_value_query_string_parameters

        def initialize
          @base64 = false
          @body = ''
          @headers = {}
          @method = 'GET'
          @multi_value_query_string_parameters = {}
          @path = '/'
          @path_parameters = {}
          @query = {}
          @request_context = {}
        end

        def to_h
          {
            'body' => @body,
            'headers' => @headers,
            'httpMethod' => @method,
            'isBase64Encoded' => @base64,
            'multiValueQueryStringParameters' => @multi_value_query_string_parameters,
            'path' => @path,
            'pathParameters' => @path_parameters,
            'queryStringParameters' => @query,
            'requestContext' => @request_context
          }
        end
      end
    end
  end
end
